//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.Vuelos = new HashSet<Vuelo>();
        }
    
        public int idRutaPK { get; set; }
        public string codigoVuelo { get; set; }
        public string companiaAerea { get; set; }
        public string diaSemana { get; set; }
        public string pais { get; set; }
        public string arrivalDeparture { get; set; }
        public int capacidadMaxima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelo> Vuelos { get; set; }
    }
}
